import type { Metadata } from "next";
import "./globals.css";

import { Header } from "../components/Header";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body>
        <Providers>
          <div className="mt-20">
            <Header />

            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
